version: '3'
services:
  decidim:
    image: ghcr.io/codeandomexico/decidim-monterrey/production:latest
    ports:
      - '80:3000'
    env_file:
      - .env
    volumes:
      - ~/decidim-storage:/decidim/storage
      - ~/decidim-log:/decidim/log
      - tmp_cache:/decidim/tmp
    command: "bundle exec bin/rails s -b 0.0.0.0"
  # ------------------------------
  # Delayed Job
  delayed_job:
    image: ghcr.io/codeandomexico/decidim-monterrey/production:latest
    command: "bundle exec rake jobs:work"
    env_file:
      - .env
    volumes:
      - ~/decidim-log:/decidim/log
      - tmp_cache:/decidim/tmp
    depends_on:
      - decidim
  # ------------------------------
  # Clockwork
  clockwork:
    image: ghcr.io/codeandomexico/decidim-monterrey/production:latest
    command: "bundle exec clockwork config/clockwork.rb"
    env_file:
      - .env
    volumes:
      - ~/decidim-log:/decidim/log
      - tmp_cache:/decidim/tmp
    depends_on:
      - decidim
volumes:
  tmp_cache: {}
