version: '3'
services:
  decidim:
    image: ghcr.io/codeandomexico/decidim-monterrey/staging:latest
    ports:
      - '80:3000'
    env_file:
      - .env
    volumes:
      - ~/decidim-storage:/decidim/storage
      - ~/decidim-log:/decidim/log
      - tmp_cache:/decidim/tmp
    entrypoint: /decidim/docker/entrypoints/decidim.sh
    command: "/decidim/bin/rails s -b 0.0.0.0"
    depends_on:
      redis:
        condition: service_healthy
  # Sidekiq
  sidekiq:
    image: ghcr.io/codeandomexico/decidim-monterrey/staging:latest
    command: "bundle exec sidekiq -C config/sidekiq.yml"
    env_file:
      - .env
    depends_on:
      - decidim

  # Sidekiq
  clockwork:
    image: ghcr.io/codeandomexico/decidim-monterrey/staging:latest
    command: "bundle exec clockwork config/clockwork.rb"
    depends_on:
      - decidim
  # ------------------------------
  # redis
  redis:
    image: redis
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  tmp_cache: {}
  redis-data: {}
