version: '3'
services:
  decidim:
    image: ghcr.io/codeandomexico/decidim-monterrey/production:latest
    ports:
      - '80:3000'
    env_file:
      - .env
    command: '/decidim/bin/rails s -b 0.0.0.0'
