version: '3'
services:
  decidim:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports:
      - '3000:3000'
    env_file:
      - .env
    tmpfs:
      - /decidim/tmp
    command: '/decidim/bin/rails s -b 0.0.0.0'
