name: Imagen de staging

on:
  push:
    branches:
      - staging

jobs:
  docker-image-staging:
    runs-on: ubuntu-latest
    environment: staging
    if: github.ref == 'refs/heads/staging'

    steps:
      - uses: actions/checkout@v2

      - name: Construir imagen Docker
        uses: VaultVulp/gp-docker-action@1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: staging
          image-tag: latest
          custom-args: --build-arg RAILS_ENV=production --build-arg FORCE_SSL=false --build-arg SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }} --build-arg MAILER_SENDER=${{ secrets.MAILER_SENDER }}
          dockerfile: docker/decidim.Dockerfile
          build-context: .
